mkdir rule_based_solutions
mkdir ratings
mkdir genetic_solutions
mkdir bayes_solutions

mkdir rule_based_solutions/targosz_p59_ex1
mkdir rule_based_solutions/targosz_p59_ex2
mkdir rule_based_solutions/targosz_p59_ex4
mkdir rule_based_solutions/targosz_p60_ex6
mkdir rule_based_solutions/targosz_p60_ex7
mkdir rule_based_solutions/targosz_p60_ex10
mkdir rule_based_solutions/targosz_p60_ex11
mkdir rule_based_solutions/targosz_p60_ex12
mkdir rule_based_solutions/targosz_p238_ex106
mkdir rule_based_solutions/targosz_p238_ex109

mkdir ratings/targosz_p59_ex1
mkdir ratings/targosz_p59_ex2
mkdir ratings/targosz_p59_ex4
mkdir ratings/targosz_p60_ex6
mkdir ratings/targosz_p60_ex7
mkdir ratings/targosz_p60_ex10
mkdir ratings/targosz_p60_ex11
mkdir ratings/targosz_p60_ex12
mkdir ratings/targosz_p238_ex106
mkdir ratings/targosz_p238_ex109

mkdir genetic_solutions/targosz_p59_ex1
mkdir genetic_solutions/targosz_p59_ex2
mkdir genetic_solutions/targosz_p59_ex4
mkdir genetic_solutions/targosz_p60_ex6
mkdir genetic_solutions/targosz_p60_ex7
mkdir genetic_solutions/targosz_p60_ex10
mkdir genetic_solutions/targosz_p60_ex11
mkdir genetic_solutions/targosz_p60_ex12
mkdir genetic_solutions/targosz_p238_ex106
mkdir genetic_solutions/targosz_p238_ex109

mkdir bayes_solutions/targosz_p59_ex1
mkdir bayes_solutions/targosz_p59_ex2
mkdir bayes_solutions/targosz_p59_ex4
mkdir bayes_solutions/targosz_p60_ex6
mkdir bayes_solutions/targosz_p60_ex7
mkdir bayes_solutions/targosz_p60_ex10
mkdir bayes_solutions/targosz_p60_ex11
mkdir bayes_solutions/targosz_p60_ex12
mkdir bayes_solutions/targosz_p238_ex106
mkdir bayes_solutions/targosz_p238_ex109
