# add ```filters.disabled+=play.filters.csrf.CSRFFilter``` to application.conf to disable CSRF
openapi: 3.0.1
info:
  title: Harmony Solver API
  description: 'Main api providing core functionalities of HarmonySolver'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://localhost:9000/harmonytools

paths:
  /walking-bass:
    post:
      summary: Post new walking bass exercise
      operationId: solveWalkingBassExercise
      requestBody:
        required: true
        description: Exercise object that needs to be send
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalkingBassExerciseRequestDto'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalkingBassExerciseSolutionDto'

components:
  schemas:
    #WALKING-BASS
    WalkingBassExerciseRequestDto:
      type: object
      required:
        - meter
        - measures
      properties:
        meter:
          $ref: '#/components/schemas/MeterDto'
          description: Meter of solution in format <nominator>/<denominator> f.e. '3/4', '6/8'
        measures:
          type: array
          items:
            $ref: '#/components/schemas/WalkingBassMeasureDto'

    WalkingBassMeasureDto:
      required:
        - notes
      properties:
        notes:
          type: array
          items:
            $ref: '#/components/schemas/BassGeneratorInputDto'

    JazzNoteDto:
      type: object
      required:
        - pitch
        - chordComponent
      properties:
        pitch:
          type: integer
          description: Pitch of the jazz note
        chordComponent:
          type: integer
          description: Explains the relation with the chord


    BassGeneratorInputDto:
      type: object
      required:
        - basicChordNotes
        - colorChordNotes
        - scaleNotes
        - isStrongBeat
        - isOnBeat
        - duration
        - chordSymbol
        - isFirst
      properties:
        basicChordNotes:
          type: array
          description: List of basic chord notes
          items:
            $ref: '#/components/schemas/JazzNoteDto'
        colorChordNotes:
          type: array
          description: List of color chord notes
          items:
            $ref: '#/components/schemas/JazzNoteDto'
        scaleNotes:
          type: array
          description: List of scale notes
          items:
            $ref: '#/components/schemas/JazzNoteDto'
        isStrongBeat:
          type: boolean
          description: Indicates if the note is on the strong beat
        isOnBeat:
          type: boolean
          description: Indicates if the note is on the beat
        duration:
          type: double
        chordSymbol:
          type: string
        isFirst:
          type: boolean

    WalkingBassExerciseSolutionDto:
      type: object
      required:
        - exercise
        - pitches
      properties:
        exercise:
          type: object
          $ref: '#/components/schemas/WalkingBassExerciseRequestDto'
          description: Given exercise as input
        pitches:
          type: array
          description: List of pitches that solution contains
          items:
            type: integer

    MeterDto:
      type: array
      items:
        type: integer